"""Constants for Vimar By-me Alarm."""

DOMAIN = "vimar_alarm"

CONF_SCAN_INTERVAL = "scan_interval"
CONF_VERIFY_SSL = "verify_ssl"

DEFAULT_PORT = 443
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_TIMEOUT = 8
DEFAULT_VERIFY_SSL = False
DEFAULT_TCP_PORT = 45211

STATE_DISARMED = "1"
STATE_ARMED = "2"

INTRUSION_EVENT_TYPES = frozenset({70, 71, 83})
POWER_FAILURE_EVENT_TYPE = 58
POWER_RESTORE_EVENT_TYPE = 82

PARTITIONS_CONTAINER = "_DPAD_VIMAR_SAI_PARTITIONS_CONTAINER"
PLATFORMS = ["alarm_control_panel", "binary_sensor"]
